#include "../decrypt.hpp"
#include "../elf.hpp"
#include "../iso.hpp"
#include "internal.hpp"

#include <algorithm>
#include <cctype>
#include <chrono>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string_view>

namespace psprecomp::project_detail
{

	std::string iso_patch_tool_source()
	{
		return R"CPP(// Generated by psprism: rebuilds a PSP disc image while preserving the
// logical block address (LBA) of every file that is not explicitly replaced.
// See src/project/iso_patch_template.cpp (iso_patch_tool_source) in the
// psprism repository for
// the full rationale.
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

constexpr std::uint32_t sector_size = 2048U;

struct Replacement {
  std::string iso_path;
  std::filesystem::path local_path;
};

std::string normalized_path(std::string_view value) {
  std::string result;
  result.reserve(value.size());
  for (const auto character : value) {
    if (character == '\\') {
      result.push_back('/');
    } else if (character != '/') {
      result.push_back(static_cast<char>(
          std::toupper(static_cast<unsigned char>(character))));
    } else if (!result.empty() && result.back() != '/') {
      result.push_back('/');
    }
  }
  while (!result.empty() && result.front() == '/') {
    result.erase(result.begin());
  }
  while (!result.empty() && result.back() == '/') {
    result.pop_back();
  }
  return result;
}

std::uint32_t read_u32(const std::vector<std::uint8_t> &data,
                       std::size_t offset) {
  if (offset > data.size() || data.size() - offset < 4U) {
    throw std::runtime_error("truncated ISO 9660 field");
  }
  return static_cast<std::uint32_t>(data[offset]) |
         static_cast<std::uint32_t>(data[offset + 1U]) << 8U |
         static_cast<std::uint32_t>(data[offset + 2U]) << 16U |
         static_cast<std::uint32_t>(data[offset + 3U]) << 24U;
}

// Every 32-bit numeric field in an ISO 9660 directory record (and the PVD)
// is stored twice: once little-endian, once big-endian, back to back. Both
// copies must stay consistent or strict readers reject the image.
void write_both_endian_u32(std::fstream &stream, std::uint64_t le_offset,
                           std::uint32_t value) {
  std::uint8_t le[4] = {
      static_cast<std::uint8_t>(value & 0xFFU),
      static_cast<std::uint8_t>((value >> 8U) & 0xFFU),
      static_cast<std::uint8_t>((value >> 16U) & 0xFFU),
      static_cast<std::uint8_t>((value >> 24U) & 0xFFU)};
  std::uint8_t be[4] = {le[3], le[2], le[1], le[0]};
  stream.seekp(static_cast<std::streamoff>(le_offset));
  stream.write(reinterpret_cast<const char *>(le), 4);
  stream.write(reinterpret_cast<const char *>(be), 4);
  if (!stream) {
    throw std::runtime_error("failed to patch ISO 9660 directory record");
  }
}

struct DirectoryRecordInfo {
  std::uint64_t record_offset{}; // absolute byte offset of the record itself
  std::uint32_t extent{};
  std::uint32_t size{};
};

std::vector<std::uint8_t> read_range(std::ifstream &stream,
                                     std::uint64_t offset, std::size_t size) {
  stream.clear();
  stream.seekg(static_cast<std::streamoff>(offset));
  std::vector<std::uint8_t> result(size);
  if (size != 0U) {
    stream.read(reinterpret_cast<char *>(result.data()),
                static_cast<std::streamsize>(size));
  }
  if (!stream) {
    throw std::runtime_error("failed while reading ISO image");
  }
  return result;
}

std::string record_name(const std::uint8_t *record, std::size_t length) {
  if (length < 34U) {
    throw std::runtime_error("invalid ISO 9660 directory record");
  }
  const auto name_length = record[32];
  if (33U + name_length > length) {
    throw std::runtime_error("truncated ISO 9660 file name");
  }
  if (name_length == 1U && (record[33] == 0U || record[33] == 1U)) {
    return {};
  }
  std::string name(reinterpret_cast<const char *>(record + 33U), name_length);
  if (const auto version = name.find(';'); version != std::string::npos) {
    name.resize(version);
  }
  while (!name.empty() && name.back() == '.') {
    name.pop_back();
  }
  return name;
}

// Walks the ISO 9660 tree rooted at the primary volume descriptor and
// records, for every file, where its directory record physically lives in
// the image (so it can be patched later) alongside its current extent/size.
std::map<std::string, DirectoryRecordInfo>
index_directory_records(std::ifstream &stream) {
  std::map<std::string, DirectoryRecordInfo> result;

  const auto descriptor = read_range(stream, 16ULL * sector_size, sector_size);
  if (descriptor[0] != 1U ||
      std::string_view(reinterpret_cast<const char *>(descriptor.data() + 1U),
                       5U) != "CD001" ||
      descriptor[6] != 1U) {
    throw std::runtime_error("input is not an ISO 9660 image");
  }
  const auto root_length = descriptor[156];
  if (root_length < 34U || 156U + root_length > descriptor.size()) {
    throw std::runtime_error("ISO image has an invalid root directory");
  }
  const auto root_extent = read_u32(descriptor, 158U);
  const auto root_size = read_u32(descriptor, 166U);

  struct PendingDirectory {
    std::string path;
    std::uint32_t extent;
    std::uint32_t size;
  };
  std::vector<PendingDirectory> pending{{{}, root_extent, root_size}};
  std::set<std::pair<std::uint32_t, std::uint32_t>> visited;
  while (!pending.empty()) {
    const auto directory = pending.back();
    pending.pop_back();
    if (!visited.emplace(directory.extent, directory.size).second) {
      continue;
    }
    const auto base_offset =
        static_cast<std::uint64_t>(directory.extent) * sector_size;
    const auto bytes = read_range(stream, base_offset, directory.size);
    std::size_t cursor = 0;
    while (cursor < bytes.size()) {
      const auto length = bytes[cursor];
      if (length == 0U) {
        cursor = ((cursor / sector_size) + 1U) * sector_size;
        continue;
      }
      if (cursor + length > bytes.size() || length < 34U) {
        throw std::runtime_error("invalid ISO directory record");
      }
      const auto *record = bytes.data() + cursor;
      const auto name = record_name(record, length);
      if (!name.empty()) {
        const auto extent = read_u32(bytes, cursor + 2U);
        const auto size = read_u32(bytes, cursor + 10U);
        const bool is_directory = (record[25] & 2U) != 0U;
        auto entry_path = directory.path.empty() ? name
                                                  : directory.path + "/" + name;
        result[normalized_path(entry_path)] =
            DirectoryRecordInfo{base_offset + cursor, extent, size};
        if (is_directory) {
          pending.push_back({entry_path, extent, size});
        }
      }
      cursor += length;
    }
  }
  return result;
}

void patch_iso_preserving_layout(
    const std::filesystem::path &original, const std::filesystem::path &output,
    const std::vector<Replacement> &replacements) {
  {
    std::ifstream probe(original, std::ios::binary);
    if (!probe) {
      throw std::runtime_error("cannot open ISO image: " + original.string());
    }
  }

  std::map<std::string, DirectoryRecordInfo> records;
  {
    std::ifstream source(original, std::ios::binary);
    records = index_directory_records(source);
  }

  std::filesystem::create_directories(output.parent_path());
  std::filesystem::copy_file(
      original, output, std::filesystem::copy_options::overwrite_existing);

  std::fstream target(output,
                      std::ios::binary | std::ios::in | std::ios::out);
  if (!target) {
    throw std::runtime_error("cannot open ISO image for patching: " +
                             output.string());
  }
  target.seekg(0, std::ios::end);
  const auto original_size = static_cast<std::uint64_t>(target.tellg());
  if (original_size % sector_size != 0U) {
    throw std::runtime_error("ISO image size is not sector aligned");
  }
  std::uint64_t append_sector = original_size / sector_size;
  const auto original_sector_count = append_sector;

  for (const auto &replacement : replacements) {
    const auto key = normalized_path(replacement.iso_path);
    const auto found = records.find(key);
    if (found == records.end()) {
      throw std::runtime_error("ISO image has no file at: " +
                               replacement.iso_path);
    }
    const auto &info = found->second;

    std::ifstream local(replacement.local_path,
                        std::ios::binary | std::ios::ate);
    if (!local) {
      throw std::runtime_error("cannot open replacement file: " +
                               replacement.local_path.string());
    }
    const auto local_size = static_cast<std::uint64_t>(local.tellg());
    local.seekg(0);
    std::vector<char> content(local_size);
    if (local_size != 0U) {
      local.read(content.data(), static_cast<std::streamsize>(local_size));
    }
    if (!local) {
      throw std::runtime_error("failed reading replacement file: " +
                               replacement.local_path.string());
    }

    const std::uint64_t needed_sectors =
        (local_size + sector_size - 1U) / sector_size;
    const std::uint64_t original_sectors =
        (static_cast<std::uint64_t>(info.size) + sector_size - 1U) /
        sector_size;

    std::uint64_t data_sector;
    if (original_sectors != 0U && needed_sectors <= original_sectors) {
      // Fits in the space the original file already occupied: keep the
      // same LBA so every other file's raw-sector references stay valid.
      data_sector = info.extent;
    } else {
      // Does not fit: append past the current end of the image (sector
      // aligned) and repoint only this file's directory record there.
      data_sector = append_sector;
      append_sector += needed_sectors;
    }

    const std::uint64_t write_offset = data_sector * sector_size;
    const std::uint64_t padded_size =
        (data_sector == info.extent ? original_sectors : needed_sectors) *
        sector_size;
    target.seekp(static_cast<std::streamoff>(write_offset));
    target.write(content.data(), static_cast<std::streamsize>(local_size));
    for (std::uint64_t i = local_size; i < padded_size; ++i) {
      target.put('\0');
    }
    if (!target) {
      throw std::runtime_error("failed writing replacement content for: " +
                               replacement.iso_path);
    }

    write_both_endian_u32(target, info.record_offset + 2U,
                          static_cast<std::uint32_t>(data_sector));
    write_both_endian_u32(target, info.record_offset + 10U,
                          static_cast<std::uint32_t>(local_size));
  }

  if (append_sector > original_sector_count) {
    // Keep the PVD's declared volume size consistent with the (now larger)
    // image; several readers sanity-check this against the actual size.
    write_both_endian_u32(target, 16ULL * sector_size + 80U,
                          static_cast<std::uint32_t>(append_sector));
  }

  target.flush();
  if (!target) {
    throw std::runtime_error("failed finalizing patched ISO image: " +
                             output.string());
  }
}

} // namespace

int main(int argc, char **argv) {
  try {
    if (argc < 3) {
      std::cerr << "usage: " << argv[0]
                << " <original.iso> <output.iso> [<iso_path>=<local_file> "
                   "...]\n";
      return 1;
    }
    const std::filesystem::path original = argv[1];
    const std::filesystem::path output = argv[2];
    std::vector<Replacement> replacements;
    for (int i = 3; i < argc; ++i) {
      const std::string_view argument(argv[i]);
      const auto separator = argument.find('=');
      if (separator == std::string_view::npos) {
        std::cerr << "expected <iso_path>=<local_file>, got: " << argument
                  << '\n';
        return 1;
      }
      replacements.push_back(
          {std::string(argument.substr(0, separator)),
           std::filesystem::path(argument.substr(separator + 1U))});
    }
    patch_iso_preserving_layout(original, output, replacements);
    std::cout << "Built PSP ISO: " << output.string() << '\n';
    return 0;
  } catch (const std::exception &error) {
    std::cerr << "iso_patch: " << error.what() << '\n';
    return 1;
  }
}
)CPP";
	}

} // namespace psprecomp::project_detail
