#include "../emitter.hpp"
#include "internal.hpp"
#include <psprecomp/allegrex_decoder.hpp>
#include <psprecomp/vfpu.hpp>
#include <algorithm>
#include <array>
#include <bit>
#include <cctype>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

#include "../emitter.hpp"

namespace psprecomp {
using namespace detail;

void emit_cpp(const ElfImage& image, const std::filesystem::path& output,
              const CodeMap* code_map) {
    (void)code_map;
    const auto relocated = relocated_words(image);
    // Decode everything first so a failed translation never leaves a partial
    // file.
    std::ostringstream cases;
    for (const auto& section : image.executable_sections) {
        for (std::size_t offset = 0; offset < section.bytes.size();
             offset += 4) {
            const auto pc =
                section.address + static_cast<std::uint32_t>(offset);
            const auto instruction = word_at(section, offset);
            cases << "        case " << hex(pc) << ": // " << hex(instruction)
                  << "\n            "
                  << emit_instruction(pc, instruction, relocated.contains(pc))
                  << "\n            break;\n";
        }
    }

    std::ofstream stream(output, std::ios::binary | std::ios::trunc);
    if (!stream) {
        throw std::runtime_error("cannot open output: " + output.string());
    }
    stream
        << "// Generated by psprecomp. Do not edit.\n"
           "#include <psprecomp/runtime.hpp>\n"
           "#include <psprecomp/vfpu.hpp>\n\n"
           "namespace psprecomp::generated {\n\n"
           "void run(State& state, std::uint32_t return_address, "
           "std::uint64_t max_steps) {\n"
           "    state.stop_reason = StopReason::running;\n";
    if (image.preferred_base != 0U) {
        stream << "    if (state.memory_base == 0U) state.memory_base = "
               << hex(image.preferred_base) << ";\n";
    }
    stream
        << "    for (std::uint64_t step = 0; step < max_steps; ++step) {\n"
           "        if (state.pc == return_address && !state.branch_pending) "
           "{\n"
           "            state.stop_reason = StopReason::returned;\n"
           "            return;\n"
           "        }\n"
           "        const bool apply_delayed_branch = state.branch_pending;\n"
           "        const std::uint32_t delayed_target = state.branch_target;\n"
           "        state.branch_pending = false;\n"
           "        const std::uint32_t current_pc = state.pc;\n"
           "        state.pc = current_pc + 4U;\n"
           "        using namespace psprecomp;\n"
           "        switch (current_pc - state.memory_base) {\n"
        << cases.str()
        << "        default:\n"
           "            state.stop_reason = StopReason::invalid_pc;\n"
           "            state.fault_address = current_pc;\n"
           "            return;\n"
           "        }\n"
           "        state.gpr[0] = 0;\n"
           "        if (state.stop_reason != StopReason::running) { return; }\n"
           "        if (apply_delayed_branch) { state.pc = delayed_target; }\n"
           "    }\n"
           "    state.stop_reason = StopReason::step_limit;\n"
           "}\n\n"
           "} // namespace psprecomp::generated\n";
    if (!stream) {
        throw std::runtime_error("failed while writing output: " +
                                 output.string());
    }
}

} // namespace psprecomp
